/**
 * Reads the seeded SQLite file and writes its bytes as a base64 string
 * into a real TS module (lib/generated/db-blob.ts).
 *
 * Why: Vercel's serverless filesystem is read-only, so lib/sqlite.ts
 * stages a writable copy into /tmp before Prisma connects. That code
 * builds the source path from DATABASE_URL at *runtime*, which Next's
 * file tracer can't see at build time — outputFileTracingIncludes was
 * configured for this but the file still wasn't landing in the deployed
 * function (`/var/task/prisma/dev.db` missing), leaving production with
 * "Error code 14: Unable to open the database file" on every route.
 *
 * Embedding the bytes as a real `import` sidesteps tracing heuristics
 * entirely — bundlers always include modules that are actually
 * imported. lib/sqlite.ts falls back to this snapshot when the bundled
 * file isn't where it's expected.
 *
 * Runs at the end of `npm run seed` (keeps local dev's copy fresh) and
 * again after refresh-catalog in scripts/vercel-build.mjs, right before
 * `next build`, so the embedded snapshot matches whatever is on disk
 * when the bundle is produced.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { config } from "dotenv";

const root = path.resolve(import.meta.dirname, "..");

// Standalone scripts don't get Next.js's automatic .env.local loading.
config({ path: path.join(root, ".env.local"), quiet: true });
config({ path: path.join(root, ".env"), quiet: true });

const raw = (process.env.DATABASE_URL || "file:./dev.db").trim();
const rel = raw.replace(/^file:(\/\/)?/, "");

// Prisma's sqlite connector resolves a relative `file:` URL against the
// schema file's directory (prisma/), not process.cwd() — so a local
// DATABASE_URL of "file:./dev.db" actually lives at prisma/dev.db, even
// though the same relative path means something else once it's rebased
// onto process.cwd() at Vercel runtime (see lib/sqlite.ts). Try both.
const candidates = path.isAbsolute(rel)
  ? [rel]
  : [path.join(root, rel), path.join(root, "prisma", path.basename(rel))];
const src = candidates.find((p) => existsSync(p));

const base64 = src ? readFileSync(src).toString("base64") : "";
if (!base64) {
  console.warn(`[generate-db-blob] no db found in [${candidates.join(", ")}] — writing an empty placeholder`);
}

const outDir = path.join(root, "lib", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  path.join(outDir, "db-blob.ts"),
  "// AUTO-GENERATED by scripts/generate-db-blob.mjs — do not edit by hand.\n" +
    "// Base64 snapshot of the seeded SQLite database, embedded so it's\n" +
    "// always part of the JS bundle. See lib/sqlite.ts.\n" +
    `export const DB_BASE64 = ${JSON.stringify(base64)};\n`
);

if (base64) {
  console.log(
    `[generate-db-blob] embedded ${(base64.length / 1024).toFixed(0)} KB (base64) from ${src}`
  );
}

